# fly.toml app configuration file generated for robert-martin-dev on 2023-11-07T16:31:17-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "robert-martin-dev"
primary_region = "atl"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[checks]
  [checks.status]
    port = 3000
    type = "http"
    interval = "10s"
    timeout = "2s"
    grace_period = "5s"
    method = "GET"
    path = "/healthcheck"
    protocol = "http"
    tls_skip_verify = false
